spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-royal-salad-aeccrvv0-pooler.c-2.us-east-2.aws.neon.tech:5432/personal-manager-expense}
    username: ${DB_USERNAME:app_pme}
    password: ${DB_PASSWORD:Although6$Tiny$Depress}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: INFO
    com.aldahirzamora: DEBUG