spring:
  application:
    name: personal-manager-expense-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

app:
  jwt:
    secret: ${JWT_SECRET:change-this-super-secret-key-min-32-chars-long}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
